import { Founders } from "./enums/founders.enum";
import { AcademicTopics } from "./enums/topics.enum";
import { CardProps } from "./types/card.interface";

export const entries: CardProps[] = [
  {
    display: "dark",
    title: "React Useless Hooks",
    theme: "playful",
    founderName: Founders.Narze,
    topic: AcademicTopics.React,
    imagePath: "/images/react-useless-hooks.png",
    githubUrl: "https://github.com/narze/react-useless",
    detail: {
      contributingMarkdown: undefined,
      descriptionMarkdown: "Eiei",
      inspiredBy: "",
      keywords: [],
    },
  },
  {
    display: "light",
    title: "Coffee to Code",
    theme: "mindful",
    founderName: Founders.Narze,
    topic: AcademicTopics.LanguageDiversity,
    imagePath: "/images/coffee-to-code.jpg",
    githubUrl: "https://github.com/narze/coffee-to-code",
  },
  {
    display: "light",
    title: "Torpleng - ต่อเพลง",
    theme: "playful",
    founderName: Founders.Narze,
    topic: AcademicTopics.Vue,
    imagePath: "/images/torpleng.jpg",
    githubUrl: "https://github.com/narze/torpleng",
  },
  {
    display: "dark",
    title: "Nunmun - นั่นมัน....!",
    theme: "playful",
    founderName: Founders.Narze,
    topic: AcademicTopics.Svelte,
    imagePath: "/images/nunmun.png",
    githubUrl: "https://github.com/narze/nunmun",
  },
  {
    display: "dark",
    title: "Awesome Cheab Quotes - คำคมเฉียบ ๆ",
    theme: "playful",
    founderName: Founders.Narze,
    topic: AcademicTopics.Vue,
    githubUrl: "https://github.com/narze/awesome-cheab-quotes",
    imagePath: undefined,
  },
  {
    display: "light",
    title: "Dumb Questions - คำถามโง่ ๆ",
    theme: "playful",
    founderName: Founders.Narze,
    topic: AcademicTopics.Git,
    githubUrl: "https://github.com/narze/dumb-questions-th",
    imagePath: undefined,
  },
  {
    display: "light",
    title: "Watasalim",
    theme: "playful",
    founderName: Founders.Narze,
    topic: AcademicTopics.Next,
    imagePath: "/images/watasalim.png",
    githubUrl: "https://github.com/narze/awesome-salim-quotes",
  },
  {
    display: "dark",
    title: "Deploydeemai.today",
    theme: "mindful",
    founderName: Founders.Narze,
    topic: AcademicTopics.Svelte,
    imagePath: "/images/deploydeemai.png",
    githubUrl: "https://github.com/narze/deploydeemai.today",
  },
  {
    display: "dark",
    title: "MukPakPak - มุกแป๊ก ๆ",
    theme: "playful",
    founderName: Founders.Tinarskii,
    topic: AcademicTopics.Solid,
    imagePath: "/images/mukpakpak.jpeg",
    githubUrl: "https://github.com/tinarskii/mukpakpak",
  },
];
